name: CameronMC
version: '${project.version}'
main: rocks.learnercouncil.cameronmc.spigot.CameronMC
description: A general purpose plugin made for the Learner Server
api-version: 1.17
depend:
  - PlaceholderAPI
commands:
  cameron:
    aliases:
      - cameronmc
    permission: cameron.commands.cameron